Documentation.

diff --git a/functions/virtualenv_sh_init b/functions/virtualenv_sh_init
--- a/functions/virtualenv_sh_init
+++ b/functions/virtualenv_sh_init
@@ -1,27 +1,31 @@
 #!/bin/sh
 
-if [ -z "$WORKON_HOME" ]; then
-    WORKON_HOME="$HOME/.virtualenvs"
+if [ -z "${WORKON_HOME}" ]; then
+    WORKON_HOME="${HOME}/.virtualenvs"
 fi
 
-if [ -e "$WORKON_HOME" ] && [ ! -d "$WORKON_HOME" ]; then
-    echo "ERROR: $WORKON_HOME exists but is not a directory."
+if [ -e "${WORKON_HOME}" ] && [ ! -d "${WORKON_HOME}" ]; then
+    echo "ERROR: ${WORKON_HOME} exists but is not a directory."
     return 1
 fi
 
 _virtualenv_sh_hook_functions=
 
-if [ ! -e "$WORKON_HOME" ]; then
-    echo "Creating $WORKON_HOME" >&2
-    mkdir "$WORKON_HOME" || return 2
+if [ ! -e "${WORKON_HOME}" ]; then
+    echo "Creating ${WORKON_HOME}" >&2
+    mkdir "${WORKON_HOME}" || return 2
 
     for hook in initialize \
                 premkvirtualenv postmkvirtualenv \
                 prermvirtualenv postrmvirtualenv \
                 preactivate postactivate \
                 predeactivate postdeactivate; do
-        echo "#!/bin/sh" > "$WORKON_HOME"/$hook    
+        echo "#!/bin/sh" > "${WORKON_HOME}"/${hook}    
     done
+
+    #for hook in preactivate postactivate predeactivate postdeactivate; do
+    #    echo "echo \"echo local \\\"\\\$@\\\"\" > \${WORKON_HOME}/\$2/bin/$hook" >> "${WORKON_HOME}"/postmkvirtualenv
+    #done
 fi
 
 virtualenv_sh_init_features
